### ISSUE TITLE
Force close

### ISSUE THREAD

**Issue by muafakul** [nkzawa/socket.io-android-chat#10]
when i compile using jar library and not using granle ..its force close ..so sad :'(

**Comment by nkzawa** [comment]
Can you explain the details of your problem?

**Comment by muafakul** [comment]
I am not using grandle. Then I download the maven repositories ..i donload socket blabalba.jar and engine.blabala.jar ..and then i put them into libs ..i succesed compile the apo but when i run the app .it shown forced close.....please how to compile using AIDE. ...really i just have android phone

**Comment by muafakul** [comment]
Please help me ...very very please try to use AIDE to compile this source :(

**Comment by nkzawa** [comment]
This repository supports only gradle. I have never used AIDE. Please find a way by yourself if you'd like to try on another environment.
Anyway I think you have to install all dependencies, see https://github.com/nkzawa/socket.io-android-chat/blob/master/app/build.gradle#L35 for that.

**Comment by muafakul** [comment]
:(

2015-07-05 9.12 GMT+07.00, Naoyuki Kanezawa <notifications@github.com>:

**Comment by muafakul** [comment]
Could you compile using jar?

**Comment by muafakul** [comment]
Brlow is thr logcat.
I hope you can fix it..




07-05 10:22:17.309 1910 1910 I     dalvikvm com.github.nkzawa.socketio.androidchat     Could not find method android.view.ViewGroup.onRtlPropertiesChanged, referenced from method android.support.v7.widget.Toolbar.onRtlPropertiesChanged
07-05 10:22:17.309 1910 1910 W     dalvikvm com.github.nkzawa.socketio.androidchat     VFY: unable to resolve virtual method 12742: Landroid/view/ViewGroup;.onRtlPropertiesChanged (I)V
07-05 10:22:17.319 1910 1910 D     dalvikvm com.github.nkzawa.socketio.androidchat     VFY: replacing opcode 0x6f at 0x000a
07-05 10:22:17.319 1910 1910 I     dalvikvm com.github.nkzawa.socketio.androidchat     Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.internal.widget.TintTypedArray.getChangingConfigurations
07-05 10:22:17.319 1910 1910 W     dalvikvm com.github.nkzawa.socketio.androidchat     VFY: unable to resolve virtual method 373: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
07-05 10:22:17.329 1910 1910 D     dalvikvm com.github.nkzawa.socketio.androidchat     VFY: replacing opcode 0x6e at 0x0004
07-05 10:22:17.329 1910 1910 I     dalvikvm com.github.nkzawa.socketio.androidchat     Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.internal.widget.TintTypedArray.getType
07-05 10:22:17.329 1910 1910 W     dalvikvm com.github.nkzawa.socketio.androidchat     VFY: unable to resolve virtual method 395: Landroid/content/res/TypedArray;.getType (I)I
07-05 10:22:17.329 1910 1910 D     dalvikvm com.github.nkzawa.socketio.androidchat     VFY: replacing opcode 0x6e at 0x0006
07-05 10:22:17.439 1910 1910 D     dalvikvm com.github.nkzawa.socketio.androidchat     DexOpt: couldn't find field Lcom/github/nkzawa/socketio/client/Manager$Options;.hostnameVerifier
07-05 10:22:17.439 1910 1910 W     dalvikvm com.github.nkzawa.socketio.androidchat     VFY: unable to resolve instance field 6231
07-05 10:22:17.439 1910 1910 D     dalvikvm com.github.nkzawa.socketio.androidchat     VFY: replacing opcode 0x54 at 0x002c
07-05 10:22:17.449 1910 1910 D     AndroidRuntime com.github.nkzawa.socketio.androidchat     Shutting down VM
07-05 10:22:17.459 1910 1910 W     dalvikvm com.github.nkzawa.socketio.androidchat     threadid=1: thread exiting with uncaught exception (group=0x41309438)
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     FATAL EXCEPTION: main
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     java.lang.NoSuchFieldError: com.github.nkzawa.socketio.client.Manager$Options.hostnameVerifier
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     at com.github.nkzawa.socketio.client.Manager.<init>(Manager.java:125)
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     at com.github.nkzawa.socketio.client.IO.socket(IO.java:76)
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     at com.github.nkzawa.socketio.client.IO.socket(IO.java:41)
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     at com.github.nkzawa.socketio.client.IO.socket(IO.java:37)
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     at com.github.nkzawa.socketio.androidchat.MainFragment.block$3076(MainFragment.java:49)
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     at com.github.nkzawa.socketio.androidchat.MainFragment.<init>(MainFragment.java:56)
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     at java.lang.Class.newInstanceImpl(Native Method)
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     at java.lang.Class.newInstance(Class.java:1319)
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socke

**Comment by muafakul** [comment]
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     at android.app.ActivityThread.access$700(ActivityThread.java:143)
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     at android.os.Handler.dispatchMessage(Handler.java:99)
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     at android.os.Looper.loop(Looper.java:137)
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     at android.app.ActivityThread.main(ActivityThread.java:4963)
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     at java.lang.reflect.Method.invokeNative(Native Method)
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     at java.lang.reflect.Method.invoke(Method.java:511)
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
07-05 10:22:17.499 1910 1910 E     AndroidRuntime com.github.nkzawa.socketio.androidchat     at dalvik.system.NativeStart.main(Native Method)

**Comment by nkzawa** [comment]
Unfortunately, I can't help you with this issue as already told.
I edited the title of it, so that other people might be able to help you.

**Comment by muafakul** [comment]
:(
Minggu, 05 Juli 2015, Naoyuki Kanezawa <notifications@github.com> menulis:
> Unfortunately, I can't help you with this issue as already told.
> I edited the title of it, so that other people might be able to help you.
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci6.googleusercontent.com/proxy/W_qwxzc34YYtoS_2JqE0nXP9uf_2Uw0a20EBW35eUM7gnKIDHACveM3SyCy7MLKwSRabKx6L3dXFNKknds0UMRtE3xGDGn1UnUhuih5CYf-y4502jVQ5o_fFUJph_9gPtj5Crdl4j-wFsvRFwYkJpMEEYoY7sQ=s0-d-e1-ft#https://github.com/notifications/beacon/AMePYRaOQ8B-xkjdhNHIUFowyy0s2POUks5oaMMXgaJpZM4FRp0N.gif
>

**Comment by skyrylyuk** [comment]
Hello,  as @nkzawa mention in message from "commented on Jul 5, 2015" 

> Anyway, I think you have to install all dependencies

But, I have one addition note, use all transient dependency.
