### ISSUE TITLE
Xhr poll error

### ISSUE THREAD

**Issue by kishen007** [nkzawa/socket.io-android-chat#117]
2020-12-15 11:15:26.683 27145-27455/com.infinitevariable.ivuniverse W/System.err: com.github.nkzawa.engineio.client.EngineIOException: xhr poll error
2020-12-15 11:15:26.683 27145-27455/com.infinitevariable.ivuniverse W/System.err:     at com.github.nkzawa.engineio.client.Transport.onError(Transport.java:65)
2020-12-15 11:15:26.683 27145-27455/com.infinitevariable.ivuniverse W/System.err:     at com.github.nkzawa.engineio.client.transports.PollingXHR.access$100(PollingXHR.java:17)
2020-12-15 11:15:26.683 27145-27455/com.infinitevariable.ivuniverse W/System.err:     at com.github.nkzawa.engineio.client.transports.PollingXHR$6$1.run(PollingXHR.java:125)
2020-12-15 11:15:26.683 27145-27455/com.infinitevariable.ivuniverse W/System.err:     at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
2020-12-15 11:15:26.683 27145-27455/com.infinitevariable.ivuniverse W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-12-15 11:15:26.683 27145-27455/com.infinitevariable.ivuniverse W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-12-15 11:15:26.683 27145-27455/com.infinitevariable.ivuniverse W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-12-15 11:15:26.683 27145-27455/com.infinitevariable.ivuniverse W/System.err: Caused by: java.net.SocketTimeoutException: failed to connect to socket-io-chat.now.sh/198.51.100.10 (port 443) from /100.121.240.252 (port 33756) after 10000ms
2020-12-15 11:15:26.683 27145-27455/com.infinitevariable.ivuniverse W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:191)
2020-12-15 11:15:26.683 27145-27455/com.infinitevariable.ivuniverse W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:135)
2020-12-15 11:15:26.683 27145-27455/com.infinitevariable.ivuniverse W/System.err:     at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
2020-12-15 11:15:26.683 27145-27455/com.infinitevariable.ivuniverse W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
2020-12-15 11:15:26.683 27145-27455/com.infinitevariable.ivuniverse W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
2020-12-15 11:15:26.683 27145-27455/com.infinitevariable.ivuniverse W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)

**Comment by igorlopesfaria** [comment]
same issue

**Comment by fluffyspace** [comment]
My problem was with url, to connect to local server with Android Studio emulator you have to follow these steps -> https://medium.com/livefront/how-to-connect-your-android-emulator-to-a-local-web-service-47c380bff350

**Comment by thisames** [comment]
I solved this problem by updating `socket.io-client-java` to the latest version
