### ISSUE TITLE
This has a conflict with okhttp dispatcher

### ISSUE THREAD

**Issue by whowazit** [nkzawa/socket.io-android-chat#29]
I tried to connect using this library and I'm also using okhttp but it has a conflict with okhttp dispatcher.

03-10 13:39:12.721 5216-5275/com.shima.thebizgames E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
03-10 13:39:12.721 5216-5275/com.shima.thebizgames E/AndroidRuntime: java.lang.NoSuchMethodError: com.squareup.okhttp.internal.Internal.callEngineGetConnection
03-10 13:39:12.721 5216-5275/com.shima.thebizgames E/AndroidRuntime:     at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(WebSocketCall.java:154)
03-10 13:39:12.721 5216-5275/com.shima.thebizgames E/AndroidRuntime:     at com.squareup.okhttp.ws.WebSocketCall.access$000(WebSocketCall.java:42)
03-10 13:39:12.721 5216-5275/com.shima.thebizgames E/AndroidRuntime:     at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(WebSocketCall.java:102)
03-10 13:39:12.721 5216-5275/com.shima.thebizgames E/AndroidRuntime:     at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
03-10 13:39:12.721 5216-5275/com.shima.thebizgames E/AndroidRuntime:     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
03-10 13:39:12.721 5216-5275/com.shima.thebizgames E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
03-10 13:39:12.721 5216-5275/com.shima.thebizgames E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
03-10 13:39:12.721 5216-5275/com.shima.thebizgames E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:856)

**Comment by TheWeakestLink** [comment]
I have the same problem too and can't seem to find a fix yet. I'm also using Retrofit and Socket.io

**Comment by bingdow** [comment]
In my case don't really need to include okhttp in build.gradle file can still use it and make it work with Retrofit.
After remove okhttp in app/build.gradle file everything seems okay.
