### ISSUE TITLE
here is a crash for using this lib

### ISSUE THREAD

**Issue by dahutiger** [nkzawa/socket.io-android-chat#56]
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at com.github.nkzawa.parseqs.ParseQS.decode(SourceFile:28)
	at com.github.nkzawa.engineio.client.Socket.<init>(SourceFile:187)
	at com.github.nkzawa.engineio.client.Socket.<init>(SourceFile:162)
	at com.github.nkzawa.socketio.client.Manager$Engine.<init>(SourceFile:542)
	at com.github.nkzawa.socketio.client.Manager$1.run(SourceFile:221)
	at com.github.nkzawa.thread.EventThread.exec(SourceFile:50)
	at com.github.nkzawa.socketio.client.Manager.open(SourceFile:214)
	at com.github.nkzawa.socketio.client.Manager.open(SourceFile:204)
	at com.github.nkzawa.socketio.client.Socket$3.run(SourceFile:121)
	at com.github.nkzawa.thread.EventThread$2.run(SourceFile:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

version is 0.3.0.
It happens When I change my WIFI.

**Comment by vasskob** [comment]
Have the same issue.

**Comment by cgowthamanmca** [comment]
private void initSocket() {
        try {
            mSocket = IO.socket(SocketConstant.CHAT_SERVER_URL + "?subscription_id=" + AppUtils.getSocketKey());
        } catch (URISyntaxException e) {
            Crashlytics.logException(e);
        }
    }
