### ISSUE TITLE
java.lang.IllegalArgumentException Android 26

### ISSUE THREAD

**Issue by omar-othmann** [nkzawa/socket.io-android-chat#80]
i got every time this error and i don't know why

`E/AndroidRuntime: FATAL EXCEPTION: EventThread
                  Process: app, PID: 11909
                  java.lang.IllegalArgumentException
                      at java.nio.Buffer.limit(Buffer.java:276)
                      at com.github.nkzawa.engineio.parser.Parser.decodePayload(Parser.java:232)
                      at com.github.nkzawa.engineio.client.transports.Polling._onData(Polling.java:132)
                      at com.github.nkzawa.engineio.client.transports.Polling.onData(Polling.java:104)
                      at com.github.nkzawa.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:113)
                      at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                      at java.lang.Thread.run(Thread.java:764)
`

in class: java.nio.Buffer.limit
`public final Buffer limit(int newLimit) {
        if ((newLimit > capacity) || (newLimit < 0))
            throw new IllegalArgumentException();
        limit = newLimit;
        if (position > limit) position = limit;
        if (mark > limit) mark = -1;
        return this;
    }`

**Comment by omar-othmann** [comment]
version 0.4.2:
`implementation ('com.github.nkzawa:socket.io-client:0.4.2'){
        exclude group: 'org.json', module: 'json'
    }`

**Comment by aap01** [comment]
I am getting the same issue in my emulator.
Is there a solution to this issue? @omar-othmann
